"""IR → PostgreSQL DDL (F1.3). Rules live in docs/db-rules.md; rationale in DECISIONS.md.

- Identifiers are lowercased and double-quoted (`"library_branches"`), so LLM-written SQL resolves whether
  it quotes or not. Two identifiers in one scope that differ only by case → `DDLEmitError`.
- `emit_tables()` creates tables WITHOUT foreign keys (any order, cycles allowed); `emit_foreign_keys()`
  adds them as named `ALTER TABLE ... ADD CONSTRAINT` statements after data load.
- ENUM → VARCHAR(max literal length) + CHECK (col IN (...)); AUTO_INCREMENT/SERIAL → GENERATED BY DEFAULT
  AS IDENTITY; DATETIME → TIMESTAMP; JSON → JSONB; unknown → TEXT.
- CHECK expressions are re-parsed with sqlglot so column references are quoted + lowercased consistently.
"""

from __future__ import annotations

import sqlglot
from sqlglot import exp
from sqlglot.errors import ParseError

from .models import Column, ColumnType, ForeignKey, Schema, Table

MAX_IDENTIFIER_LENGTH = 63  # PostgreSQL NAMEDATALEN - 1


class DDLEmitError(ValueError):
    """The IR cannot be represented in PostgreSQL (identifier collision / too long)."""


def ident(name: str) -> str:
    """Lowercased, double-quoted identifier."""
    lowered = name.lower()
    if len(lowered) > MAX_IDENTIFIER_LENGTH:
        raise DDLEmitError(f"identifier {name!r} is longer than {MAX_IDENTIFIER_LENGTH} characters")
    return '"' + lowered.replace('"', '""') + '"'


def qualified(table: str, schema_name: str | None) -> str:
    return f"{ident(schema_name)}.{ident(table)}" if schema_name else ident(table)


def column_type_sql(col: Column) -> str:
    match col.type:
        case ColumnType.INTEGER:
            return "INTEGER"
        case ColumnType.BIGINT:
            return "BIGINT"
        case ColumnType.SMALLINT:
            return "SMALLINT"
        case ColumnType.DECIMAL:
            return f"NUMERIC({col.precision or 10}, {col.scale or 0})"
        case ColumnType.FLOAT:
            return "DOUBLE PRECISION"
        case ColumnType.BOOLEAN:
            return "BOOLEAN"
        case ColumnType.VARCHAR:
            return f"VARCHAR({col.length})" if col.length else "TEXT"
        case ColumnType.CHAR:
            return f"CHAR({col.length or 1})"
        case ColumnType.TEXT:
            return "TEXT"
        case ColumnType.DATE:
            return "DATE"
        case ColumnType.DATETIME:
            return "TIMESTAMP"
        case ColumnType.TIME:
            return "TIME"
        case ColumnType.ENUM:
            return f"VARCHAR({max(col.max_length or 1, 1)})"
        case ColumnType.JSON:
            return "JSONB"
        case ColumnType.UUID:
            return "UUID"
        case _:
            return "TEXT"


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def column_sql(col: Column) -> str:
    parts = [ident(col.name), column_type_sql(col)]
    if col.auto_increment and col.type.is_integer:
        parts.append("GENERATED BY DEFAULT AS IDENTITY")
    if not col.nullable:
        parts.append("NOT NULL")
    if col.default is not None and not col.auto_increment:
        parts.append(f"DEFAULT {col.default}")
    if col.unique and not col.primary_key:
        parts.append("UNIQUE")
    if col.type is ColumnType.ENUM and col.enum_values:
        values = ", ".join(sql_literal(v) for v in col.enum_values)
        parts.append(f"CHECK ({ident(col.name)} IN ({values}))")
    return " ".join(parts)


def quote_check_expression(expression: str) -> str:
    """Re-render a CHECK expression with lowercased, quoted column references."""
    try:
        tree = sqlglot.parse_one(expression, read="postgres")
    except ParseError:
        return expression  # leave as-is; Postgres will report a precise error if it is invalid
    for column in tree.find_all(exp.Column):
        identifier = column.this
        if isinstance(identifier, exp.Identifier):
            identifier.set("this", identifier.name.lower())
            identifier.set("quoted", True)
    return tree.sql(dialect="postgres")


def _assert_unique_lowercase(names: list[str], scope: str) -> None:
    seen: dict[str, str] = {}
    for name in names:
        low = name.lower()
        if low in seen and seen[low] != name:
            raise DDLEmitError(f"{scope}: {seen[low]!r} and {name!r} collide when lowercased")
        seen[low] = name


def emit_table(table: Table, schema_name: str | None = None) -> str:
    _assert_unique_lowercase(table.column_names, f"table {table.name}")
    lines = [column_sql(c) for c in table.columns]
    if table.primary_key:
        lines.append("PRIMARY KEY (" + ", ".join(ident(c) for c in table.primary_key) + ")")
    for uq in table.unique_constraints:
        prefix = f"CONSTRAINT {ident(uq.name)} " if uq.name else ""
        lines.append(prefix + "UNIQUE (" + ", ".join(ident(c) for c in uq.columns) + ")")
    for chk in table.checks:
        prefix = f"CONSTRAINT {ident(chk.name)} " if chk.name else ""
        lines.append(prefix + f"CHECK ({quote_check_expression(chk.expression)})")
    body = ",\n  ".join(lines)
    return f"CREATE TABLE {qualified(table.name, schema_name)} (\n  {body}\n)"


def emit_tables(schema: Schema, schema_name: str | None = None) -> list[str]:
    """CREATE TABLE statements without foreign keys, in declaration order."""
    _assert_unique_lowercase(schema.table_names, "schema")
    return [emit_table(t, schema_name) for t in schema.tables]


def fk_constraint_name(table: Table, fk: ForeignKey, used: set[str]) -> str:
    base = fk.name or f"fk_{table.name}_{'_'.join(fk.columns)}"
    name = base.lower()[:MAX_IDENTIFIER_LENGTH]
    suffix = 1
    while name in used:
        suffix += 1
        tail = f"_{suffix}"
        name = base.lower()[: MAX_IDENTIFIER_LENGTH - len(tail)] + tail
    used.add(name)
    return name


def emit_foreign_keys(schema: Schema, schema_name: str | None = None) -> list[str]:
    """ALTER TABLE ... ADD CONSTRAINT statements for every FK (run after data load)."""
    statements: list[str] = []
    used: set[str] = set()
    for table in schema.tables:
        for fk in table.foreign_keys:
            name = fk_constraint_name(table, fk, used)
            cols = ", ".join(ident(c) for c in fk.columns)
            ref_cols = ", ".join(ident(c) for c in fk.ref_columns)
            stmt = (
                f"ALTER TABLE {qualified(table.name, schema_name)} ADD CONSTRAINT {ident(name)} "
                f"FOREIGN KEY ({cols}) REFERENCES {qualified(fk.ref_table, schema_name)} ({ref_cols})"
            )
            if fk.on_delete:
                stmt += f" ON DELETE {fk.on_delete}"
            statements.append(stmt)
    return statements


def emit_sequence_resets(schema: Schema, schema_name: str | None = None) -> list[str]:
    """After explicit-id inserts, move identity sequences past the max id (next = max + 1, or 1 if empty)."""
    statements: list[str] = []
    for table in schema.tables:
        for col in table.columns:
            if col.auto_increment and col.type.is_integer:
                relation = qualified(table.name, schema_name)
                rel_literal = relation.replace("'", "''")
                statements.append(
                    f"SELECT setval(pg_get_serial_sequence('{rel_literal}', '{col.name.lower()}'), "
                    f"COALESCE(MAX({ident(col.name)}), 0) + 1, false) FROM {relation}"
                )
    return statements


def emit_schema_script(schema: Schema, schema_name: str | None = None) -> str:
    """Complete, re-runnable script: optional CREATE SCHEMA, tables, then foreign keys."""
    parts: list[str] = []
    if schema_name:
        parts.append(f"CREATE SCHEMA IF NOT EXISTS {ident(schema_name)}")
    parts.extend(emit_tables(schema, schema_name))
    parts.extend(emit_foreign_keys(schema, schema_name))
    return ";\n\n".join(parts) + ";\n"
