"""F1.3 — IR → PostgreSQL DDL emitter (pure; the integration test executes the output against Postgres)."""

import pytest

from genai_data_gen_project.schema.models import Column, ColumnType, Table
from genai_data_gen_project.schema.parser import parse_ddl
from genai_data_gen_project.schema.postgres_ddl import (
    DDLEmitError,
    column_sql,
    column_type_sql,
    emit_foreign_keys,
    emit_schema_script,
    emit_sequence_resets,
    emit_table,
    emit_tables,
    ident,
    quote_check_expression,
)


def col(name: str, ctype: ColumnType, **kw: object) -> Column:
    return Column(name=name, type=ctype, raw_type=ctype.value.upper(), **kw)  # type: ignore[arg-type]


@pytest.mark.parametrize(
    ("column", "expected"),
    [
        (col("a", ColumnType.INTEGER), "INTEGER"),
        (col("a", ColumnType.BIGINT), "BIGINT"),
        (col("a", ColumnType.DECIMAL, precision=10, scale=2), "NUMERIC(10, 2)"),
        (col("a", ColumnType.DECIMAL), "NUMERIC(10, 0)"),
        (col("a", ColumnType.FLOAT), "DOUBLE PRECISION"),
        (col("a", ColumnType.VARCHAR, length=255), "VARCHAR(255)"),
        (col("a", ColumnType.VARCHAR), "TEXT"),
        (col("a", ColumnType.CHAR, length=2), "CHAR(2)"),
        (col("a", ColumnType.DATETIME), "TIMESTAMP"),
        (col("a", ColumnType.ENUM, enum_values=["Hardcover", "E-book"]), "VARCHAR(9)"),
        (col("a", ColumnType.JSON), "JSONB"),
        (col("a", ColumnType.UNKNOWN), "TEXT"),
    ],
)
def test_type_mapping(column: Column, expected: str) -> None:
    assert column_type_sql(column) == expected


def test_identifiers_are_lowercased_and_quoted() -> None:
    assert ident("Library_Branches") == '"library_branches"'
    assert ident('we"ird') == '"we""ird"'
    with pytest.raises(DDLEmitError):
        ident("x" * 64)


def test_column_sql_variants() -> None:
    pk = col("book_id", ColumnType.INTEGER, auto_increment=True, primary_key=True, nullable=False)
    assert column_sql(pk) == '"book_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL'
    isbn = col("ISBN", ColumnType.VARCHAR, length=20, unique=True, nullable=False)
    assert column_sql(isbn) == '"isbn" VARCHAR(20) NOT NULL UNIQUE'
    status = col("status", ColumnType.ENUM, enum_values=["Active", "Closed"], default="'Active'")
    assert (
        column_sql(status)
        == "\"status\" VARCHAR(6) DEFAULT 'Active' CHECK (\"status\" IN ('Active', 'Closed'))"
    )
    ts = col("created", ColumnType.DATETIME, default="CURRENT_TIMESTAMP")
    assert column_sql(ts) == '"created" TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
    flag = col("ok", ColumnType.BOOLEAN, default="TRUE", nullable=False)
    assert column_sql(flag) == '"ok" BOOLEAN NOT NULL DEFAULT TRUE'


def test_check_expressions_get_quoted_lowercase_columns() -> None:
    assert quote_check_expression("Rating >= 1 AND rating <= 5") == '"rating" >= 1 AND "rating" <= 5'
    assert quote_check_expression("status IN ('a', 'b')") == "\"status\" IN ('a', 'b')"
    assert quote_check_expression("not ( valid sql") == "not ( valid sql"  # left to Postgres


def test_emit_table_and_fks_for_restaurants(sample_ddl: dict[str, str]) -> None:
    schema = parse_ddl(sample_ddl["restaurants"])
    tables = emit_tables(schema, "ds_x")
    assert len(tables) == 7 and all("FOREIGN KEY" not in t for t in tables)
    reviews = emit_table(schema.table("Reviews"), "ds_x")
    assert reviews.startswith('CREATE TABLE "ds_x"."reviews" (')
    assert '"review_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL' in reviews
    assert 'PRIMARY KEY ("review_id")' in reviews
    assert 'CHECK ("rating" >= 1 AND "rating" <= 5)' in reviews
    fks = emit_foreign_keys(schema, "ds_x")
    assert len(fks) == sum(len(t.foreign_keys) for t in schema.tables)
    assert fks[0] == (
        'ALTER TABLE "ds_x"."orders" ADD CONSTRAINT "fk_orders_customer_id" FOREIGN KEY ("customer_id") '
        'REFERENCES "ds_x"."customers" ("customer_id")'
    )
    script = emit_schema_script(schema, "ds_x")
    assert script.startswith('CREATE SCHEMA IF NOT EXISTS "ds_x";')
    assert script.index("CREATE TABLE") < script.index("ALTER TABLE") and script.rstrip().endswith(";")


def test_named_fk_on_delete_and_duplicate_names() -> None:
    schema = parse_ddl(
        "CREATE TABLE p (id INT PRIMARY KEY);"
        "CREATE TABLE c (id INT PRIMARY KEY, p_id INT REFERENCES p(id) ON DELETE CASCADE,"
        " FOREIGN KEY (p_id) REFERENCES p(id));"
        "ALTER TABLE c ADD CONSTRAINT FK_Custom FOREIGN KEY (p_id) REFERENCES p(id) ON DELETE SET NULL;"
    )
    fks = emit_foreign_keys(schema)
    assert [f.split('CONSTRAINT "')[1].split('"')[0] for f in fks] == [
        "fk_c_p_id",
        "fk_c_p_id_2",
        "fk_custom",
    ]
    assert fks[0].endswith("ON DELETE CASCADE") and fks[2].endswith("ON DELETE SET NULL")


def test_sequence_resets_only_for_identity_columns(sample_ddl: dict[str, str]) -> None:
    schema = parse_ddl(sample_ddl["company"])
    resets = emit_sequence_resets(schema, "ds_x")
    assert len(resets) == 7
    assert resets[0] == (
        "SELECT setval(pg_get_serial_sequence('\"ds_x\".\"companies\"', 'company_id'), "
        'COALESCE(MAX("company_id"), 0) + 1, false) FROM "ds_x"."companies"'
    )


def test_case_collisions_are_rejected() -> None:
    table = Table(name="t", columns=[col("Id", ColumnType.INTEGER), col("id", ColumnType.INTEGER)])
    with pytest.raises(DDLEmitError, match="collide"):
        emit_table(table)
